---
name: ShipIt-Step-CheckVersionsMatch
version: 0.01
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Check that all modules with a $VERSION match
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Find::Rule: 0
  ShipIt: 0
build_requires:
  Test::More: 0
provides:
  ShipIt::Step::CheckVersionsMatch:
    file: lib/ShipIt/Step/CheckVersionsMatch.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
